added infinite scroll and masonry layout
Unlair/qulix-task pull request #1
Opened 2018-04-04 09:08 UTC by Unlair

2018-04-04 10:33 UTC, barmidrol requested changes
Изучи стайлгайд (https://github.com/airbnb/javascript/tree/master/react) и исправь все ошибки, на которые я указал.

2018-04-04 10:33 UTC, barmidrol commented on src/App.js
> +        this.state.search.search(nextState.valueText, nextState.offset)
`search.search` выглядит как-то не очень. Проблема с неймингом.

2018-04-04 10:33 UTC, barmidrol commented on src/App.js
> +            (window.innerHeight + window.scrollY) >= (document.body.offsetHeight - 1)
Очень интересная конструкция.
```
if (
    (condition)
) {}
```

2018-04-04 10:33 UTC, barmidrol commented on src/App.js
> +            this.infiniteSearch(this.state.valueText, this.state.offset);
Бесконечный поиск? Это как?

2018-04-04 10:33 UTC, barmidrol commented on src/App.js
> +                        <SearchBar updateText={this.updateText}/>
`updateText` не совсем корректно. Подумай, как сделать получше.

2018-04-04 10:33 UTC, barmidrol commented on src/components/Content.css
> +/*}*/
Закомментированный код никому не нужен, если это не коммантарии. VCS всю твою историю хранит, можешь не волноваться за свой код :)

2018-04-04 10:33 UTC, barmidrol commented on src/components/Content.css
> +/*}*/
Нет пустой строки в конце файла.

2018-04-04 10:33 UTC, barmidrol commented on src/components/Content.js
> +                {this.props.data.length ? <Masonry>{this.renderList(this.props.data)}</Masonry> : <p>No items!</p>}
Обращай внимание на стиль кода.

https://github.com/airbnb/javascript/tree/master/react#spacing

2018-04-04 10:33 UTC, barmidrol commented on src/services/searchService.js
> +            fetch('http://api.giphy.com/v1/gifs/search?q=' + searchValue + '&api_key=wZ7TY2vuJXe9lk8ngjHNI2dkpwAssmEU&limit=30&offset=' + offset)
Слой для работы с HTTP запросами по-хорошему стоит вынести в отдельный сервис.

2018-04-04 10:33 UTC, barmidrol commented on src/services/searchService.js
> +                                    widthFull: pic.images.original.width,
`pic.images.original.width` --> `widthFull`
Почему не `widthOriginal` ?

2018-04-04 10:33 UTC, barmidrol commented on src/services/searchService.js
> +                                    widthThumbnail: pic.images.downsized.width,
Аналогично, почему не `widthDownsized`?

2018-04-05 11:22 UTC, maxmlkhn commented on src/App.js
> +            this.setState({offset:0});
Нет пробела.

2018-04-05 11:25 UTC, Unlair commented on src/App.js
> -                        <SearchBar updateText={this.updateText} updateSlider={this.updateSlider}/>
Пробел.

2018-04-05 13:29 UTC, maxmlkhn commented on src/App.js
> +                        <SearchBar changeText={this.changeText}/>
Пробел.

2018-04-05 13:29 UTC, Unlair commented on src/components/Modal.js
> +                    alt="gifModal" src={this.props.data.original}
Заметил. Исправил.

2018-04-05 13:31 UTC, Unlair commented on src/components/Modal.js
> +                    />
Заметил. Исправил.

2018-04-06 13:17 UTC, barmidrol approved these changes

2018-04-06 13:18 UTC, merged